name: build-windows
#triggered on push
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build    
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTS=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: Run tests
      run: |
        cd build/bin/${{matrix.configuration}}
        ./Tests.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: test-win
        path: build/bin/${{matrix.configuration}}/Tests.exe
        if: matrix.configuration == 'Release' 
