name: build
#triggered on push
on: [push, pull_request]

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu, macos]
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build    
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTS=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: Run tests
      run: |
        cd bin
        ./Tests

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build    
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTS=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: Run tests
      run: |
        cd bin/${{matrix.configuration}}
        .\Tests.exe
