name: build-windows
#triggered on push
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build    
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTS=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: Run tests
      run: |
        cd build/bin/${{matrix.configuration}}
        ./Tests.exe

    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: build/bin/${{matrix.configuration}}/Tests.exe
        if: matrix.configuration == 'Release' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
